package com.pilatos.jdmrest.enums;

public enum Brand {
    ALFA_ROMEO, AUDI, BENTLEY, BMW, BUICK, CADILLAC, CHEVROLET, CHRYSLER, FIAT, FORD, GENESIS, GMC, HONDA, HYUNDAI, JAGUAR, JEEP, KIA, LAND_ROVER, LEXUS, LOTUS, MASERATI, MAZDA, MERCEDES_BENZ, MINI, MISTUBITSHI, NISSAN, POLESTAR, PONTIAC, RAM, RIVIAN, ROLLS_ROYCE, SAAB, SATURN, SMART, SUBARU, SUZUKI, TESLA, TOYOTA, VOLKSWAGEN, VOLVO
}

